project:
  type: website

website:
  title: "ACC–R&D"
  navbar:
    left:
      - text: "Articles"
        href: articles/index.qmd
      # - text: "Projects"
      #   href: projects/index.qmd
      # - text: "Discrete"
      #   href: discrete/index.qmd
      - about.qmd
    right:
      - href: https://www.acc-designs.com
        text: ACC-Designs
        icon: box-arrow-up

  sidebar: 
    - title: "Articles"
      style: "docked"
      contents: 
        - articles/index.qmd
        - articles/basics.qmd

    # - title: "Projects"
    #   contents: 
    #     - projects/index.qmd


format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
  pdf: default

execute: 
  freeze: false


